### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by skgupta507** [0ME9A/react-portfolio#2]
hi
i hosted this site on vercel but i got only a white screen how can i fix this

**Comment by 0ME9A** [comment]
Hi @skgupta507,

Thanks for bringing this to my attention. I actually maintain the website as an open-source project, and I've recently made some updates to the code to enhance readability and fix certain elements that were incorrect.

Regarding the issue you faced while deploying on Vercel, I investigated and found that there was an error in the packag.js file where the homepage URL was invalid. I've already addressed this issue, so you should now be able to deploy the website successfully on Vercel.

Feel free to give it another try, and let me know if you encounter any further difficulties or if there's anything else I can assist you with.

Best regards,
